#!/bin/sh
# sets permissions for ssh folders and files 

cd "$HOME"
chmod 700 "$HOME"/.ssh
chmod 600 "$HOME"/.ssh/*
chmod 644 -f  "$HOME"/.ssh/*.pub  "$HOME"/.ssh/authorized_keys  "$HOME"/.ssh/known_hosts  "$HOME"/.ssh/config
